// Dev tool — exempt from library-grade lints.
#![allow(
    clippy::pedantic,
    clippy::restriction,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::missing_docs_in_private_items
)]

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

/// Reads tests/test_manifest.json (generated by `node scripts/extract_test_manifest.mjs`)
/// and compares every test case against Rust #[test] functions to show exact coverage.
fn main() {
    let root = find_project_root();
    let manifest_path = root.join("tests/test_manifest.json");

    if !manifest_path.exists() {
        eprintln!("ERROR: tests/test_manifest.json not found.");
        eprintln!("Run: node scripts/extract_test_manifest.mjs");
        std::process::exit(1);
    }

    // ── Load manifest ──
    let manifest_str = fs::read_to_string(&manifest_path).unwrap();
    let manifest: serde_json::Value = serde_json::from_str(&manifest_str).unwrap();
    let test_cases = manifest["test_cases"].as_array().unwrap();

    // ── Collect Rust tests ──
    let rs_test_names = collect_all_rust_tests(&root);
    let _rs_test_set: BTreeSet<&str> = rs_test_names.iter().map(|s| s.as_str()).collect();

    // ── Group JS test cases by module ──
    let mut by_module: BTreeMap<String, Vec<&serde_json::Value>> = BTreeMap::new();
    for tc in test_cases {
        let module = tc["module"].as_str().unwrap_or("unknown").to_string();
        by_module.entry(module).or_default().push(tc);
    }

    // ── Group Rust tests by module (first path component under src/) ──
    let mut rs_by_module: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for name in &rs_test_names {
        // test names are like "tokenizer::types::test_name" or just "test_name"
        let module = name.split("::").next().unwrap_or("unknown").to_string();
        rs_by_module.entry(module).or_default().push(name.clone());
    }

    println!("╔══════════════════════════════════════════════════════════════════════╗");
    println!("║                csstree-rs Test Coverage Report                      ║");
    println!("║   Manifest: tests/test_manifest.json ({} cases){}║",
        test_cases.len(),
        " ".repeat(25 - test_cases.len().to_string().len()));
    println!("╚══════════════════════════════════════════════════════════════════════╝\n");

    // ── Per-module summary ──
    println!("┌────────────────────────┬──────────┬──────────┬──────────┬─────────┐");
    println!("│ Module                 │ JS Total │ Fixture  │ Inline   │ RS impl │");
    println!("├────────────────────────┼──────────┼──────────┼──────────┼─────────┤");

    let mut grand_total = 0usize;
    let mut grand_rs = 0usize;

    let module_order = [
        "tokenizer",
        "parser",
        "generator",
        "walker",
        "definition_syntax",
        "lexer",
        "utils",
        "common",
    ];

    for module in &module_order {
        let cases = by_module.get(*module);
        let total = cases.map(|c| c.len()).unwrap_or(0);
        let fixture_count = cases
            .map(|c| c.iter().filter(|t| t["category"].as_str() == Some("fixture")).count())
            .unwrap_or(0);
        let inline_count = cases
            .map(|c| c.iter().filter(|t| t["category"].as_str() == Some("inline")).count())
            .unwrap_or(0);
        let rs_count = rs_by_module.get(*module).map(|v| v.len()).unwrap_or(0);

        grand_total += total;
        grand_rs += rs_count;

        let pct_str = if total > 0 {
            format!("{:.0}%", rs_count as f64 / total as f64 * 100.0)
        } else {
            "-".to_string()
        };

        println!(
            "│ {:<22} │ {:>8} │ {:>8} │ {:>8} │ {:>4} {:>3} │",
            module, total, fixture_count, inline_count, rs_count, pct_str
        );
    }

    println!("├────────────────────────┼──────────┼──────────┼──────────┼─────────┤");
    let grand_pct = if grand_total > 0 {
        format!("{:.1}%", grand_rs as f64 / grand_total as f64 * 100.0)
    } else {
        "0%".to_string()
    };
    println!(
        "│ {:<22} │ {:>8} │          │          │ {:>4} {:>3} │",
        "TOTAL", grand_total, grand_rs, grand_pct
    );
    println!("└────────────────────────┴──────────┴──────────┴──────────┴─────────┘\n");

    // ── Per-fixture-file detail ──
    let mut by_fixture: BTreeMap<String, (usize, String)> = BTreeMap::new();
    for tc in test_cases {
        if tc["category"].as_str() == Some("fixture") {
            if let Some(file) = tc["fixture_file"].as_str() {
                let entry = by_fixture.entry(file.to_string()).or_insert((0, String::new()));
                entry.0 += 1;
                if entry.1.is_empty() {
                    entry.1 = tc["module"].as_str().unwrap_or("?").to_string();
                }
            }
        }
    }

    println!("┌──────────────────────────────────────────────────┬────────┬────────┐");
    println!("│ Fixture File                                     │ Cases  │ Status │");
    println!("├──────────────────────────────────────────────────┼────────┼────────┤");

    // Check which fixture files have Rust tests that reference them
    let rs_all_content = collect_all_rust_source(&root.join("src"), &root.join("tests"));

    for (file, (count, _module)) in &by_fixture {
        // Heuristic: check if any Rust file references this fixture file name
        let file_stem = file
            .replace(['/', '-'], "_")
            .replace(".json", "");
        let referenced = rs_all_content.contains(&file_stem)
            || rs_all_content.contains(file.as_str());
        let status = if referenced { " FOUND" } else { "  TODO" };
        println!(
            "│ {:<48} │ {:>6} │{:<7} │",
            truncate(file, 48),
            count,
            status
        );
    }
    println!("└──────────────────────────────────────────────────┴────────┴────────┘\n");

    // ── Inline test detail (show missing ones) ──
    let inline_cases: Vec<_> = test_cases
        .iter()
        .filter(|tc| tc["category"].as_str() == Some("inline"))
        .collect();

    if !inline_cases.is_empty() {
        // Group by source file
        let mut by_source: BTreeMap<String, Vec<&serde_json::Value>> = BTreeMap::new();
        for tc in &inline_cases {
            let source = tc["source_file"].as_str().unwrap_or("?").to_string();
            by_source.entry(source).or_default().push(tc);
        }

        println!("┌──────────────────────────────────────────────────────────────────────┐");
        println!("│ INLINE TEST CASES                                                    │");
        println!("├──────────────────────────────────────────────────────────────────────┤");

        for (source, cases) in &by_source {
            println!("│ {} ({} tests):", source, cases.len());
            for tc in cases {
                let desc = tc["describe"].as_str().unwrap_or("");
                let it_name = tc["it"].as_str().unwrap_or("?");
                let css = tc["css_input"].as_str().unwrap_or("");
                let label = if desc.is_empty() {
                    it_name.to_string()
                } else {
                    format!("{} > {}", desc, it_name)
                };
                let css_preview = if css.is_empty() {
                    String::new()
                } else {
                    let preview: String = css.chars().take(40).collect();
                    let ellipsis = if css.len() > 40 { "..." } else { "" };
                    format!(" [{}{}]", preview.replace('\n', "\\n"), ellipsis)
                };
                println!("│   - {}{}", truncate(&label, 50), css_preview);
            }
            println!("│");
        }
        println!("└──────────────────────────────────────────────────────────────────────┘\n");
    }

    // ── Grand summary ──
    println!("══════════════════════════════════════════════════════════════════════");
    println!(
        "  {} / {} test cases | {} Rust #[test] functions | Coverage: {}",
        grand_rs, grand_total, rs_test_names.len(), grand_pct
    );
    println!("══════════════════════════════════════════════════════════════════════");
    println!();
    println!("To sync test cases:  node scripts/extract_test_manifest.mjs");
    println!("To check coverage:   cargo run --bin test-coverage");
}

// ── Collect all Rust #[test] functions with full module path ──
fn collect_all_rust_tests(root: &Path) -> Vec<String> {
    let mut results = Vec::new();

    // src/ directory
    for entry in walk_dir(&root.join("src")) {
        if entry.extension().is_some_and(|e| e == "rs") {
            let module_path = entry
                .strip_prefix(root.join("src"))
                .unwrap()
                .to_str()
                .unwrap()
                .replace('/', "::")
                .replace(".rs", "")
                .replace("::mod", "");
            let content = fs::read_to_string(&entry).unwrap_or_default();
            for name in extract_test_functions(&content) {
                if module_path.is_empty() {
                    results.push(name);
                } else {
                    results.push(format!("{}::{}", module_path, name));
                }
            }
        }
    }

    // tests/ directory
    for entry in walk_dir(&root.join("tests")) {
        if entry.extension().is_some_and(|e| e == "rs") {
            let module = entry
                .file_stem()
                .unwrap()
                .to_str()
                .unwrap()
                .to_string();
            let content = fs::read_to_string(&entry).unwrap_or_default();
            for name in extract_test_functions(&content) {
                results.push(format!("{}::{}", module, name));
            }
        }
    }

    results.sort();
    results
}

fn collect_all_rust_source(src_dir: &Path, tests_dir: &Path) -> String {
    let mut all = String::new();
    for dir in [src_dir, tests_dir] {
        for entry in walk_dir(dir) {
            if entry.extension().is_some_and(|e| e == "rs") {
                if let Ok(content) = fs::read_to_string(&entry) {
                    all.push_str(&content);
                    all.push('\n');
                }
            }
        }
    }
    all
}

fn extract_test_functions(content: &str) -> Vec<String> {
    let mut results = Vec::new();
    let lines: Vec<&str> = content.lines().collect();

    for (i, line) in lines.iter().enumerate() {
        let trimmed = line.trim();
        if trimmed == "#[test]" || trimmed.starts_with("#[test]") {
            for next_line in &lines[(i + 1)..lines.len().min(i + 5)] {
                let next = next_line.trim();
                if next.starts_with("fn ") {
                    if let Some(name) = next
                        .strip_prefix("fn ")
                        .and_then(|s| s.split('(').next())
                        .map(|s| s.trim().to_string())
                    {
                        results.push(name);
                        break;
                    }
                }
            }
        }
    }

    results
}

// ── Helpers ──

fn find_project_root() -> PathBuf {
    let mut dir = std::env::current_dir().unwrap();
    loop {
        if dir.join("Cargo.toml").exists() {
            return dir;
        }
        if !dir.pop() {
            eprintln!("ERROR: Could not find project root");
            std::process::exit(1);
        }
    }
}

fn walk_dir(dir: &Path) -> Vec<PathBuf> {
    let mut results = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                results.extend(walk_dir(&path));
            } else {
                results.push(path);
            }
        }
    }
    results.sort();
    results
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max {
        format!("{:<width$}", s, width = max)
    } else {
        format!("{}...", &s[..max - 3])
    }
}
